; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Modules
projects[views_bulk_operations][version] = "3.2"
projects[views_bulk_operations][subdir] = "contrib"

projects[active_tags][version] = "2.x-dev"
projects[active_tags][subdir] = "contrib"

projects[admin_views][version] = "1.3"
projects[admin_views][subdir] = "contrib"

projects[ajax_comments][version] = "1.0-beta2"
projects[ajax_comments][subdir] = "contrib"

projects[akamai][version] = "2.0"
projects[akamai][subdir] = "contrib"

projects[answers][version] = "3.0"
projects[answers][subdir] = "features"

projects[auto_nodetitle][version] = "1.0"
projects[auto_nodetitle][patch][] = "http://drupal.org/files/auto_nodetitle_with_token_tree_link-1694720-7.patch"
projects[auto_nodetitle][subdir] = "contrib"

projects[background_process][type] = "module"
projects[background_process][download][type] = "git"
projects[background_process][download][url] = "http://git.drupal.org/project/background_process.git"
projects[background_process][download][branch] = "7.x-1.x"
projects[background_process][download][revision] = "10887428bea8b5745486bd76e817f3c66f16ae0d"
projects[background_process][subdir] = "contrib"

projects[best_answer][version] = "3.0"
projects[best_answer][subdir] = "features"

projects[better_exposed_filters][version] = "3.0-beta3"
projects[better_exposed_filters][subdir] = "contrib"

projects[boxes][version] = "1.2"
projects[boxes][subdir] = "contrib"

projects[ctools][version] = "1.4"
projects[ctools][subdir] = "contrib"

projects[cck_blocks][version] = "1.1"
projects[cck_blocks][subdir] = "contrib"

projects[chosen][version] = "1.0"
projects[chosen][subdir] = "contrib"

projects[content_lock][version] = "2.0"
projects[content_lock][subdir] = "contrib"

projects[context][version] = "3.0-beta4"
projects[context][subdir] = "contrib"

projects[context_http_headers][version] = "1.0"
projects[context_http_headers][subdir] = "contrib"

projects[context_og][version] = "2.1"
projects[context_og][subdir] = "contrib"

projects[date][version] = "2.6"
projects[date][subdir] = "contrib"

projects[devel][version] = "1.3"
projects[devel][subdir] = "contrib"

projects[diff][version] = "3.2"
projects[diff][subdir] = "contrib"

projects[entity][version] = "1.5"
projects[entity][subdir] = "contrib"

projects[entity2text][version] = "1.0-alpha2"
projects[entity2text][subdir] = "contrib"

projects[entitycache][version] = "1.2"
projects[entitycache][subdir] = "contrib"

projects[entityform][version] = "2.0-rc1"
projects[entityform][subdir] = "contrib"

projects[entityreference][version] = "1.1"
projects[entityreference][subdir] = "contrib"
projects[entityreference][patch][] = "http://drupal.org/files/issues/remove-null-entires-1821300-1.patch"

projects[entityreference_prepopulate][version] = "1.3"
projects[entityreference_prepopulate][subdir] = "contrib"

projects[entity_rules][version] = "1.0-alpha4"
projects[entity_rules][subdir] = "contrib"

projects[features_extra][version] = "1.0-beta1"
projects[features_extra][subdir] = "contrib"

projects[features][version] = "2.0-rc3"
projects[features][subdir] = "contrib"

projects[feeds_xpathparser][version] = "1.0"
projects[feeds_xpathparser][subdir] = "contrib"

projects[fences][version] = "1.0"
projects[fences][subdir] = "contrib"

projects[field_collection][type] = "module"
projects[field_collection][download][type] = "git"
projects[field_collection][download][url] = "http://git.drupal.org/project/field_collection.git"
projects[field_collection][download][branch] = "7.x-1.x"
projects[field_collection][download][revision] = "ae778f23f8e0968fa3a10a727c6e26c6e63309a0"
projects[field_collection][subdir] = "contrib"

projects[field_group][version] = "1.1"
projects[field_group][subdir] = "contrib"

projects[field_permissions][version] = "1.0-beta2"
projects[field_permissions][subdir] = "contrib"

projects[flag][version] = "2.0-beta9"
projects[flag][subdir] = "contrib"

projects[filter_perms][version] = "1.0"
projects[filter_perms][subdir] = "contrib"

projects[fpa][version] = "2.5"
projects[fpa][subdir] = "contrib"

projects[i18n][version] = "1.7"
projects[i18n][subdir] = "contrib"

projects[insert][version] = "1.1"
projects[insert][subdir] = "contrib"

projects[job_scheduler][version] = "2.0-alpha3"
projects[job_scheduler][subdir] = "contrib"

projects[jquery_update][version] = "2.2"
projects[job_scheduler][subdir] = "contrib"

projects[libraries][version] = "2.1"
projects[libraries][subdir] = "contrib"

projects[mail_edit][version] = "1.0"
projects[mail_edit][subdir] = "contrib"

projects[master][version] = "2.0-beta3"
projects[master][subdir] = "contrib"

projects[memcache][version] = "1.2"
projects[memcache][subdir] = "contrib"

projects[messaging][version] = "1.0-alpha2"
projects[messaging][subdir] = "contrib"

projects[metatag][version] = "1.0-rc1"
projects[metatag][subdir] = "contrib"

projects[microdata][version] = "1.0-beta2"
projects[microdata][subdir] = "contrib"

projects[module_filter][version] = "1.7"
projects[module_filter][subdir] = "contrib"

projects[nodereference_count][version] = "1.0"
projects[nodereference_count][subdir] = "contrib"

projects[nodereference_url][version] = "1.12"
projects[nodereference_url][subdir] = "contrib"

projects[og][version] = "2.5"
projects[og][subdir] = "contrib"

projects[og_extras][type] = "module"
projects[og_extras][download][type] = "git"
projects[og_extras][download][url] = "http://git.drupal.org/project/og_extras.git"
projects[og_extras][download][branch] = "7.x-1.x"
projects[og_extras][download][revision] = "b7e35876eab94894cf81cf602162ad6f01b8aa80"
projects[og_extras][subdir] = "contrib"

projects[og_massadd][type] = "module"
projects[og_massadd][download][type] = "git"
projects[og_massadd][download][url] = "http://git.drupal.org/project/og_massadd.git"
projects[og_massadd][download][branch] = "7.x-1.x"
projects[og_massadd][download][revision] = "488c3cf64d84bba942d58533c3f17aaf0caed272"
projects[og_massadd][subdir] = "contrib"

projects[og_subgroups][type] = "module"
projects[og_subgroups][download][type] = "git"
projects[og_subgroups][download][url] = "http://git.drupal.org/project/og_subgroups.git"
projects[og_subgroups][download][branch] = "7.x-2.x"
projects[og_subgroups][download][revision] = "fd8beee9bcb2482a489e6ab8d75eec87a97bb988"
projects[og_subgroups][subdir] = "contrib"

projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = "contrib"

projects[profile2][version] = "1.3"
projects[profile2][subdir] = "contrib"

projects[progress][version] = "1.4"
projects[progress][subdir] = "contrib"
	
projects[redirect][version] = "1.0-beta4"
projects[redirect][subdir] = "contrib"

projects[references][version] = "2.0"
projects[references][subdir] = "contrib"

projects[relation][version] = "1.0-rc3"
projects[relation][subdir] = "contrib"

projects[services][version] = "3.5"
projects[services][subdir] = "contrib"

projects[rules][version] = "2.3"
projects[rules][subdir] = "contrib"

projects[scheduler][version] = "1.2"
projects[scheduler][subdir] = "contrib"

projects[scheduler_workbench][version] = "1.2"
projects[scheduler_workbench][subdir] = "contrib"

projects[raven][type] = "module"
projects[raven][download][type] = "git"
projects[raven][download][url] = "http://git.drupal.org/sandbox/nodge/2305471.git"
projects[raven][download][branch] = "master"
projects[raven][subdir] = "contrib"

projects[sharedemail][type] = "module"
projects[sharedemail][download][type] = "git"
projects[sharedemail][download][url] = "http://git.drupal.org/project/sharedemail.git"
projects[sharedemail][download][branch] = "7.x-1.x"
projects[sharedemail][download][revision] = "eb35dab255adb69878c70f7a72a6512ff540226f"
projects[sharedemail][subdir] = "contrib"

projects[stringoverrides][version] = "1.8"
projects[stringoverrides][subdir] = "contrib"

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"

projects[subscriptions][version] = "1.1"
projects[subscriptions][subdir] = "contrib"

projects[token][version] = "1.5"
projects[token][subdir] = "contrib"

projects[token_filter][version] = "1.1"
projects[token_filter][subdir] = "contrib"

projects[transliteration][version] = "3.1"
projects[transliteration][subdir] = "contrib"

projects[ultimate_cron][version] = "1.9"
projects[ultimate_cron][subdir] = "contrib"

projects[user_badges][version] = "3.2"
projects[user_badges][subdir] = "contrib"

projects[userpoints][version] = "1.0"
projects[userpoints][subdir] = "contrib"

projects[userpoints_nc][version] = "1.0"
projects[userpoints_nc][subdir] = "contrib"

projects[variable][version] = "2.3"
projects[variable][subdir] = "contrib"

projects[views][version] = "3.7"
projects[views][subdir] = "contrib"

projects[views_data_export][version] = "3.0-beta6"
projects[views_data_export][subdir] = "contrib"

projects[voting_rules][version] = "1.0-alpha1"
projects[voting_rules][subdir] = "contrib"

projects[votingapi][version] = "2.11"
projects[votingapi][subdir] = "contrib"

projects[workbench][version] = "1.2"
projects[workbench][subdir] = "contrib"

projects[workbench_moderation][version] = "1.3"
projects[workbench_moderation][subdir] = "contrib"

projects[workbench_og][version] = "2.0-beta1"
projects[workbench_og][subdir] = "contrib"

projects[xmlsitemap][version] = "2.0"
projects[xmlsitemap][subdir] = "contrib"

projects[xsl_formatter][type] = "module"
projects[xsl_formatter][download][type] = "git"
projects[xsl_formatter][download][url] = "http://git.drupal.org/project/xsl_formatter.git"
projects[xsl_formatter][download][branch] = "7.x-1.x"
projects[xsl_formatter][download][revision] = "3a921bbc2bc42fd349a9a60fbe01642dd07962e8"
projects[xsl_formatter][subdir] = "contrib"